### PR TITLE
Added resources for HTML and CSS form stylings

### PR DESCRIPTION
**Pull request by ParthCheulkar**
Hi Sanchit,

As mentioned by u in ur contributing md , i have added a mock webpage that i coded which makes use of forms as well as display boxes using pure HTML and CSS. Please take a look and i hope u merge it with ur main branch. It is very beginner friendly and very less complicated.

### CODE REVIEW

**Review by sanchit2107 — APPROVED** [review]
Good work @ParthCheulkar 

Nice to see your PR here!!
I am merging it..

**Comment by ParthCheulkar** [comment]
Thankl you Sanchit

**Comment by ParthCheulkar** [comment]
Hi would it be possible for u to add the hacktober tag while merging the PR . It would help me a lot for my future endeavours

**Comment by sanchit2107** [comment]
> Hi would it be possible for u to add the hacktober tag while merging the PR . It would help me a lot for my future endeavours

Hey this repo has already tagged with hacktoberfest tag. So no need to add separately while merging.

**Comment by ParthCheulkar** [comment]
Ok thank you so much

**Pull request merged**
